# Generated by Django 4.2.3 on 2023-10-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="cylce",
            field=models.CharField(
                choices=[("Daily", "每天"), ("Weekly", "每周")],
                default="Daily",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="permissions", to="taskmanager.user"
                    ),
                ),
            ],
        ),
    ]
