# Generated by Django 4.2.3 on 2023-10-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0002_task_cylce_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningnode",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="learningnode",
            name="task_flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_node",
                to="taskmanager.taskflow",
            ),
        ),
        migrations.AlterField(
            model_name="taskflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="NOT_STARTED",
                max_length=12,
            ),
        ),
    ]
