# Generated by Django 4.2.3 on 2023-10-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0004_learningnode_progress_learningnode_time_spent"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskflow",
            name="progress_history",
            field=models.JSONField(default=list),
        ),
    ]
